### ISSUE TITLE
Site Nav menu Issue

### ISSUE THREAD

**Issue by HabibRh26** [napulen/napulen.github.io#5]
hello @napulen, First of all apology because this is not an issue related to you. I encountered the issue while trying to build my site using the `academic` theme, Can you please help me ? on the nav bar `members` tab is sitting before the `publication` tab, but when i click `members` tab, i realized that content of the `members` tab is located at the last of the home page, same goes for `award` tab, how can I serialize the content in the home page according to the nav menu serial? I attached the screenshot of `menus` file below and The gif file might also help you understand the issue : </br>
menu file </br>
![menus](https://user-images.githubusercontent.com/47397271/131241915-aaa8e36e-2dac-43b0-b5c2-15cd64861db2.png)

![academic](https://user-images.githubusercontent.com/47397271/131241633-10961774-b883-4ef9-82cc-6491fdce11c9.gif)

**Comment by napulen** [comment]
Hey @HabibRh26, you can achieve what you want by setting the `weight` attribute in the widget pages of each section of the website. 

The widget pages I'm talking about are located at `content/home/` in my repo, for example. 

If you give each of these the same "weight" as in your menu file, the order will be the one you expect.

**Comment by napulen** [comment]
Be aware that there are two `weight`s that need to be set. The one in the menu, which controls the order of the buttons, and the ones in the widget md files, which control the order of the sections in the home page.

**Comment by HabibRh26** [comment]
@napulen thanks a lot, it worked. Another ques, say I want to use the same structure of the `publication` but with a diff name how can I do it? If I use the same `widget` (which is `feature` in this case) as the `publication` then It actually renders all the contents of the `publication` section, but I want the structure of the `publication` section but the content would be different.

**Comment by napulen** [comment]
I am not sure about this one, although it sounds doable.

I encourage you to read the available documentation of the project: https://wowchemy.com/docs/content/page-features/

Also, as you know, I am not the developer of this project. My experience with it is mostly as a user. Asking in the [original repo](https://github.com/wowchemy/wowchemy-hugo-themes/issues) might give you better results.

I don't mind answering questions about things I do know.

Cheers

**Comment by HabibRh26** [comment]
@napulen  thanks. I got the solution.
